__version__ = "0.0.3"
__author__ = "Nico Schlömer"
__email__ = "nico.schloemer@gmail.com"
__copyright__ = f"Copyright (c) 2019-2020 {__author__} <{__email__}>"
__website__ = "https://github.com/nschloe/hmf"
__license__ = "License :: OSI Approved :: MIT License"
__status__ = "Development Status :: 3 - Alpha"
